---
title: "Institutional Use of Residential Buildings"
author: "Matt Khinda"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, include = FALSE}
library(sf)
library(ggspatial)
library(tidyverse)
library(here)
library(ggthemes)
```

```{r load data}
all_buildings <- read_sf(here("Data", "BASEMAP_Buildings.shp"))

all_parcels <- read_sf(here("Data", "ASSESSING_ParcelsFY2022.shp"))

boundary <- read_sf(here("Data", "BOUNDARY_CityBoundary.shp"))

badML = c("-", "--", "---", "--MD", "--R", "--R1", "--RR", "--S11")

#remove unassigned parcels
all_parcels <- all_parcels %>%
  filter(!(ML %in% badML))

assessors_data <- read_csv(here("Data", "Cambridge_Property_Database_FY2021.csv"))

overlays <- read_sf(here("Data", "CDD_ZoningOverlayDistricts.shp"))

institutional_overlays <- overlays %>%
  filter(Type == "Institutional")

#join datasets by map-lot
parcel_data <- merge(x = all_parcels, y = assessors_data, by.x = "ML", by.y = "Map/Lot")
```

```{r institutional lots}
#filter using state class codes (starting with 9 is institutional use)
institutional_lots <- parcel_data %>%
  filter(substr(StateClassCode, 1, 1) == 9)

#remove unnecessary property classes
badPropClass = c("US Government", "DCR- State Parks and Rec", "Vacant City", "Vacant Local Education", "Improved City", "Vacant, Tax Title", "Vacant (Private Ed)", "Housing, Other", "Housing Authority", "Other Open Space", "Transportation Authority", "Utility Authority", "Vacnt Transport Authorit", "Vacant Utility Authority", "Improved Public Safety", "Imprvd County Admin", "121 Corporation", "Cemeteries")

institutional_lots <- institutional_lots %>%
  filter(!(PropertyClass %in% badPropClass))


#filter for residential exterior styles
unique(institutional_lots$Exterior_Style)

goodExteriorStyles = c("APARTMENTS", "APTS-LUXURY", "CAPE-COD", "COLONIAL", "DECKER", "DUPLEX", "MULT-RESDNCE", "VICTORIAN")

institutional_residential_lots <- institutional_lots %>%
  filter(Exterior_Style %in% goodExteriorStyles | Exterior_occupancy == "SNGL-FAM-RES")


#intersect buildings with institutional lots to get institutional buildings
all_buildings <- all_buildings %>%
  st_transform(crs = st_crs(institutional_lots))

institutional_buildings <- all_buildings %>%
  mutate(num_inst = lengths(st_intersects(all_buildings, institutional_lots))) %>%
  mutate(has_inst = num_inst > 0) %>%
  filter(has_inst == TRUE)

institutional_residential_buildings <- all_buildings %>%
  mutate(num_inst = lengths(st_intersects(all_buildings, institutional_residential_lots))) %>%
  mutate(has_inst = num_inst > 0) %>%
  filter(has_inst == TRUE)


```

```{r buildings}
ggplot()+
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw", alpha = 0.2)+
  geom_sf(data = boundary, fill = NA, color = "black", linetype = "dashed") + 
  geom_sf(data=institutional_residential_buildings, aes(fill = "Institutionally-Owned Residential Buildings", color = "Institutionally-Owned Residential Buildings"), size = .2) + 
  scale_fill_manual(values = "red", name = " ")+
  scale_color_manual(values = "red", name = " ")+
  labs(caption = "Data from Cambridge Open Data Portal", title = "There are 159 Institutionally-Owned Residential Buildings in Cambridge, MA") + 
  annotation_north_arrow(
    style = north_arrow_minimal, 
    height = unit(0.75, "cm"), 
    width = unit(0.75, "cm"), 
    pad_x = unit(1, "cm"), 
    pad_y = unit(1, "cm"),) +
  annotation_scale(
    unit_category = "imperial",
    pad_x = unit(2, "cm"), 
    pad_y = unit(1, "cm"))+
  theme_map() + 
  theme(
    plot.caption = element_text(size = 10, face = "italic", hjust = 0),
    plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
    legend.text = element_text(size = 12),
    legend.position = "bottom"
    )

```


